import type { OrderDetail } from '../types/order';

// Order, OrderDetail 타입 모두 받음
export const order: OrderDetail[] = [
    {
        orderId: 'PG-20260815-0042',
        createdAt: '2026-08-15T07:58:23',
        orderStatus: 'paymentComplete',
        items: [
            {
                productId: 1,
                productName: '소니 WH-1000 헤드폰',
                color: '블랙',
                price: 389000,
                count: 1,
                iconName: 'IconHeadphones',
                itemBg: 'bg-[#E8F8F2]',
                itemText: 'text-[#22C55E]',
            },
            {
                productId: 5,
                productName: '룰루레몬 요가 매트',
                color: '민트',
                price: 89000,
                count: 2,
                iconName: 'IconYoga',
                itemBg: 'bg-[#F0FEFB]',
                itemText: 'text-[#22B1A0]',
            },
            {
                productId: 0,
                productName: '나이키 에어맥스',
                size: 270,
                color: '그린',
                price: 120000,
                count: 1,
                iconName: 'IconShoe',
                itemBg: 'bg-[#F5F6FF]',
                itemText: 'text-[#6266F1]',
            },
        ],
        
        discount: 68700,
        totalPrice: 618300, // TODO: 백엔드에서 데이터 가져와야 함
        paymentMethod: 'paygo',
        recipient: '박도윤',
        recipientAddress: '서울시 마포구 월드컵로 45, 그린빌리지 302호',
        recipientPhone: '010-7734-1298',
        carrier: 'CJ대한통운',
        trackingNumber: '987654321098',
        transactionId: 'TXN-20260815-0042',
    },
    {
        orderId: 'PG-20260909-0047',
        createdAt: '2026-09-09T07:58:23',
        orderStatus: 'shipping',
        items: [
            {
                productId: 1,
                productName: '소니 WH-1000 헤드폰',
                color: '블랙',
                price: 389000,
                count: 1,
                iconName: 'IconHeadphones',
                itemBg: 'bg-[#E8F8F2]',
                itemText: 'text-[#22C55E]',
            },
        ],
        discount: 38900,
        totalPrice: 350100, // TODO: 백엔드에서 데이터 가져와야 함
        paymentMethod: 'simplePayment',
        recipient: '최지안',
        recipientAddress: '경기도 성남시 분당구 판교역로 231, 101동 1502호',
        recipientPhone: '010-3391-6720',
        carrier: '한진택배',
        trackingNumber: '456123789045',
        transactionId: 'TXN-20260909-0047',
    },
    {
        orderId: 'PG-20260815-0046',
        createdAt: '2026-08-21T08:18:35',
        orderStatus: 'delivered',
        items: [
            {
                productId: 4,
                productName: '맥북 프로 14인치 모니터',
                color: '실버',
                price: 2490000,
                count: 1,
                iconName: 'IconDeviceLaptop',
                itemBg: 'bg-[#EEF6FF]',
                itemText: 'text-[#4D84D8]',
            },
        ],
        discount: 249000,
        totalPrice: 2241000,
        paymentMethod: 'account',
        recipient: '정하준',
        recipientAddress: '인천시 연수구 컨벤시아대로 105, 오션뷰 1804호',
        recipientPhone: '010-5528-3467',
        carrier: '롯데택배',
        trackingNumber: '778899001122',
        transactionId: 'TXN-20260821-0046',
    },
    {
        orderId: 'PG-20260815-0045',
        createdAt: '2026-08-15T08:18:35',
        orderStatus: 'cancelled',
        items: [
            {
                productId: 4,
                productName: '맥북 프로 14인치 모니터',
                color: '실버',
                price: 2490000,
                count: 1,
                iconName: 'IconDeviceLaptop',
                itemBg: 'bg-[#EEF6FF]',
                itemText: 'text-[#4D84D8]',
            },
        ],
        discount: 249000,
        totalPrice: 2241000,
        paymentMethod: 'card',
        recipient: '김하윤',
        recipientAddress: '부산시 해운대구 센텀중앙로 78, 센텀타워 909호',
        recipientPhone: '010-2247-9081',
        // 취소된 주문이라 carrier, trackingNumber 없음
        transactionId: 'TXN-20260815-0045',
    },
    {
        orderId: 'PG-20260815-0044',
        createdAt: '2026-08-15T08:18:35',
        orderStatus: 'refunded',
        items: [
            {
                productId: 3,
                productName: '유니클로 플리스 티셔츠',
                size: 105,
                color: '핑크',
                price: 59900,
                count: 3,
                iconName: 'IconShirt',
                itemBg: 'bg-[#FCF2F8]',
                itemText: 'text-[#D862A1]',
            },
        ],
        discount: 20000,
        totalPrice: 159700,
        refundAmount: 159700,
        paymentMethod: 'simplePayment',
        recipient: '이서준',
        recipientAddress: '대구시 수성구 동대구로 320, 팰리스빌 601호',
        recipientPhone: '010-6614-8853',
        carrier: 'CJ대한통운',
        trackingNumber: '334455667788',
        transactionId: 'TXN-20260815-0044',
    },
    {
        orderId: 'PG-20260815-0043',
        createdAt: '2026-08-15T08:13:20',
        orderStatus: 'paymentFailed',
        items: [
            {
                productId: 2,
                productName: '코베아 캠핑 텐트',
                color: '카키',
                price: 211000,
                count: 1,
                iconName: 'IconTent',
                itemBg: 'bg-[#FEF9EB]',
                itemText: 'text-[#E0B36B]',
            },
            {
                productId: 7,
                productName: '어반어스 데이트 백팩',
                color: '블랙',
                price: 79000,
                count: 1,
                iconName: 'IconBackpack',
                itemBg: 'bg-[#F9FBFC]',
                itemText: 'text-[#7B808C]',
            },
        ],
        discount: 29000,
        totalPrice: 261000,
        failureReason:
            '재고 부족 — 동시 주문으로 인해 결제가 처리되지 않았어요. 잔액은 차감되지 않았으니 안심하세요.',
        paymentMethod: 'paygo',
        recipient: '박서아',
        recipientAddress: '광주시 서구 상무중앙로 88, 상무캐슬 1203호',
        recipientPhone: '010-9903-2145',
        // 결제 실패로 배송 자체가 진행되지 않음. 결제도 없음 - carrier, trackingNumber, transactionId 없음
    },
];
