import type { TransactionHistory } from "../types/transactionHistory";

export const transactionHistories : TransactionHistory[] = [
    {
        id: 1,
        userId: 1,
        content: '농협 3521234123401',
        createdAt: '2026.09.14 14:23',
        type: 'charge',
        paymentMethod: '계좌이체',
        amount: 300000,
        balance: 3931000,
        statement: 'complete',
    },
    {
        id: 2,
        userId: 1,
        content: '나이키 에어맥스',
        createdAt: '2026.09.13 11:05',
        type: 'buy',
        paymentMethod: 'Paygo 잔액',
        amount: -120000,
        balance: 3631000,
        statement: 'complete',
    },
    {
        id: 3,
        userId: 1,
        content: '정하준',
        createdAt: '2026.09.09 00:20',
        type: 'transferIn',
        paymentMethod: 'Paygo 잔액',
        amount: 50000,
        balance: 3867000,
        statement: 'complete',
        counterpartyId: 5 // TODO: DB 저장될 때는 transferIn/transferOut이면 양측 거래내역 두 개 다 저장 필요
    },
    {
        id: 4,
        userId: 1,
        content: '유니클로 플리스 티셔츠',
        createdAt: '2026.09.12 14:29',
        type: 'refund',
        paymentMethod: 'Paygo 잔액',
        amount: 45000,
        balance: 3751000,
        statement: 'complete',
    },
    {
        id: 5,
        userId: 1,
        content: '최지안',
        createdAt: '2025.09.08 11:21',
        type: 'transferOut',
        paymentMethod: 'Paygo 잔액',
        amount: -30000,
        balance: 3897000,
        statement: 'complete',
        counterpartyId: 2 // TODO: DB 저장될 때는 transferIn/transferOut이면 양측 거래내역 두 개 다 저장 필요
    },
    {
        id: 6,
        userId: 1,
        content: '농협 3521234123402',
        createdAt: '2025.09.10 00:20',
        type: 'charge',
        paymentMethod: '계좌이체',
        amount: 500000,
        balance: 3917000,
        statement: 'complete',
    },
    {
        id: 7,
        userId: 1,
        content: '소니 WH-1000 헤드폰',
        createdAt: '2025.09.12 09:30',
        type: 'buy',
        paymentMethod: 'Paygo 잔액',
        amount: -89000,
        balance: 0,
        statement: 'fail',
    },
    {
        id: 8,
        userId: 1,
        content: '코베아 캠핑 텐트',
        createdAt: '2025.09.11 20:15',
        type: 'buy',
        paymentMethod: 'Paygo 잔액',
        amount: -211000,
        balance: 3706000,
        statement: 'processing',
    },
    {
        id: 9,
        userId: 1,
        content: '정지웅',
        createdAt: '2025.09.11 13:10',
        type: 'transferOut',
        paymentMethod: 'Paygo 잔액',
        amount: -20000,
        balance: 3917000,
        statement: 'complete',
        counterpartyId: 3 // TODO: DB 저장될 때는 transferIn/transferOut이면 양측 거래내역 두 개 다 저장 필요
    },
    {
        id: 10,
        userId: 1,
        content: '김현태',
        createdAt: '2025.09.11 09:40',
        type: 'transferOut',
        paymentMethod: 'Paygo 잔액',
        amount: -15000,
        balance: 3937000,
        statement: 'complete',
        counterpartyId: 4 // TODO: DB 저장될 때는 transferIn/transferOut이면 양측 거래내역 두 개 다 저장 필요
    },
];