import type { TransactionHistory } from "../types/transactionHistory";

export const transactionHistories : TransactionHistory[] = [
    {
        id: 0,
        userId: 'sonjinil',
        content: '지갑 충전',
        createdAt: '2026.09.14 14:23',
        type: 'charge',
        paymentMethod: '계좌이체',
        amount: 300000,
        balance: 3931000,
        statement: 'complete',
    },
    {
        id: 1,
        userId: 'sonjinil',
        content: '나이키 에어맥스 구매',
        createdAt: '2026.09.13 11:05',
        type: 'buy',
        paymentMethod: 'Paygo 잔액',
        amount: -120000,
        balance: 3631000,
        statement: 'complete',
    },
    {
        id: 2,
        userId: 'sonjinil',
        content: '무선 이어폰 구매',
        createdAt: '2026.09.12 09:30',
        type: 'buy',
        paymentMethod: 'Paygo 잔액',
        amount: -89000,
        balance: 0,
        statement: 'fail',
    },
    {
        id: 3,
        userId: 'sonjinil',
        content: '주문 취소 환불',
        createdAt: '2026.09.12 14:29',
        type: 'refund',
        paymentMethod: 'Paygo 잔액',
        amount: 45000,
        balance: 3751000,
        statement: 'complete',
    },
    {
        id: 4,
        userId: 'sonjinil',
        content: '캠핑 텐트 구매',
        createdAt: '2026.09.11 20:15',
        type: 'buy',
        paymentMethod: 'Paygo 잔액',
        amount: -211000,
        balance: 3706000,
        statement: 'processing',
    },
    {
        id: 5,
        userId: 'sonjinil',
        content: '지갑 충전',
        createdAt: '2026.09.10 00:20',
        type: 'charge',
        paymentMethod: '신용카드',
        amount: 500000,
        balance: 3917000,
        statement: 'complete',
    },
    {
        id: 6,
        userId: 'sonjinil',
        content: '정하준님이 입금',
        createdAt: '2026.09.09 00:20',
        type: 'transferIn',
        paymentMethod: 'Paygo 잔액',
        amount: 50000,
        balance: 3867000,
        statement: 'complete',
    },
    {
        id: 7,
        userId: 'sonjinil',
        content: '최지안님에게 출금',
        createdAt: '2026.09.08 11:21',
        type: 'transferOut',
        paymentMethod: 'Paygo 잔액',
        amount: -30000,
        balance: 3897000,
        statement: 'complete',
    },
];